//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPR.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receivers
    {
        public System.Guid Receiver_ID { get; set; }
        public string Receiver_LastName { get; set; }
        public string Receiver_FirstName { get; set; }
    
        public virtual Emails Emails { get; set; }
    }
}
