//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPR.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BD_SPR_BSEntities : DbContext
    {
        public BD_SPR_BSEntities()
            : base("name=BD_SPR_BSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Emails> Emails { get; set; }
        public DbSet<Receivers> Receivers { get; set; }
        public DbSet<ServerPerformances> ServerPerformances { get; set; }
    
        public virtual int insertEmail(string lastName, string firstName, string emailAddress, string emailSubject, string emailBody, string cPU, string rAM, string iO_Disk, string iIS_Sessions)
        {
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("emailAddress", emailAddress) :
                new ObjectParameter("emailAddress", typeof(string));
    
            var emailSubjectParameter = emailSubject != null ?
                new ObjectParameter("emailSubject", emailSubject) :
                new ObjectParameter("emailSubject", typeof(string));
    
            var emailBodyParameter = emailBody != null ?
                new ObjectParameter("emailBody", emailBody) :
                new ObjectParameter("emailBody", typeof(string));
    
            var cPUParameter = cPU != null ?
                new ObjectParameter("CPU", cPU) :
                new ObjectParameter("CPU", typeof(string));
    
            var rAMParameter = rAM != null ?
                new ObjectParameter("RAM", rAM) :
                new ObjectParameter("RAM", typeof(string));
    
            var iO_DiskParameter = iO_Disk != null ?
                new ObjectParameter("IO_Disk", iO_Disk) :
                new ObjectParameter("IO_Disk", typeof(string));
    
            var iIS_SessionsParameter = iIS_Sessions != null ?
                new ObjectParameter("IIS_Sessions", iIS_Sessions) :
                new ObjectParameter("IIS_Sessions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertEmail", lastNameParameter, firstNameParameter, emailAddressParameter, emailSubjectParameter, emailBodyParameter, cPUParameter, rAMParameter, iO_DiskParameter, iIS_SessionsParameter);
        }
    }
}
