// <auto-generated />
namespace SPR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BS_SPR_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BS_SPR_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081654192_BS_SPR_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
